version: '2'

services:
    consul:
        image: smebberson/alpine-consul
        restart: always
        expose:
            - 8500
    consului:
        image: smebberson/alpine-consul-ui
        ports:
            - 8500:8500
        restart: always
    shield-browser:
        image: securebrowsing/shield-browser:161226-22.37
        restart: always
        hostname: browser
        shm_size: 1GB
    shield-proxy:
        image: securebrowsing/squid-proxy:latest
        hostname: proxy
        restart: always
        ports:
            - "3128:3128"
    icap-server:
        image: securebrowsing/shield-icap:161226-22.36
        hostname: icap-server
        restart: always
        expose:
            - 8500
    shield-broker:
        image: securebrowsing/shield-broker:161226-22.35
        hostname: broker
        restart: always
    elk:
        image: alpin3/elk 
        hostname: elk
        ports:
            - "5601:5601"
            - "5044:5044"
    portainer:
        image: portainer/portainer
        hostname: portainer
        ports:
            - "9000:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock